apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meditracker
  template:
    metadata:
      labels:
        app: meditracker
    spec:
      containers:
      - name: meditracker
        image: alaeiq/meditracker:latest
        ports:
        - containerPort: 5000