apiVersion: v1
kind: Service
metadata:
  name: meditracker-service
  namespace: default
  labels:
    app: meditracker
spec:
  type: NodePort
  selector:
    app: meditracker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: web  # NOM DU PORT - important pour ServiceMonitor