apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meditracker-sm
  namespace: default
  labels:
    release: prometheus  # IMPORTANT : doit être "prometheus" (pas "monitoring")
spec:
  selector:
    matchLabels:
      app: meditracker  # Doit correspondre aux labels du Service
  endpoints:
    - port: web  # Utilisez le NOM du port, pas le numéro
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default  # Le namespace où se trouve votre app